import { relations, sql } from "drizzle-orm";
import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import z from "zod";

import { user } from "./auth";

/**
 * Chat Session table - represents a conversation with the AI coach
 */
export const chatSession = sqliteTable(
  "chat_session",
  {
    id: text("id").primaryKey(), // Use text ID (nanoid/uuid generated by client)
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    index("chat_session_user_id_idx").on(table.userId),
    index("chat_session_updated_at_idx").on(table.updatedAt),
  ],
);

/**
 * Chat Message table - individual messages within a session
 */
export const chatMessage = sqliteTable(
  "chat_message",
  {
    id: text("id").primaryKey(), // Text ID (nanoid/uuid)
    sessionId: text("session_id")
      .notNull()
      .references(() => chatSession.id, { onDelete: "cascade" }),
    role: text("role").$type<"user" | "assistant">().notNull(),
    content: text("content").notNull(),
    toolCalls: text("tool_calls", { mode: "json" }).$type<unknown[]>(),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
  },
  (table) => [
    index("chat_message_session_id_idx").on(table.sessionId),
    index("chat_message_created_at_idx").on(table.createdAt),
  ],
);

// ============================================================================
// Relations
// ============================================================================

export const chatSessionRelations = relations(chatSession, ({ one, many }) => ({
  user: one(user, {
    fields: [chatSession.userId],
    references: [user.id],
  }),
  messages: many(chatMessage),
}));

export const chatMessageRelations = relations(chatMessage, ({ one }) => ({
  session: one(chatSession, {
    fields: [chatMessage.sessionId],
    references: [chatSession.id],
  }),
}));

// ============================================================================
// Zod Schemas
// ============================================================================

export const selectChatSessionSchema = createSelectSchema(chatSession);
export const insertChatSessionSchema = createInsertSchema(chatSession, {
  title: (schema) => schema.min(1).max(200),
}).omit({ createdAt: true, updatedAt: true });

export const selectChatMessageSchema = createSelectSchema(chatMessage);
export const insertChatMessageSchema = createInsertSchema(chatMessage, {
  content: (schema) => schema.min(1),
}).omit({ createdAt: true });

// ============================================================================
// Type Exports
// ============================================================================

export type SelectChatSession = z.infer<typeof selectChatSessionSchema>;
export type InsertChatSession = z.infer<typeof insertChatSessionSchema>;
export type SelectChatMessage = z.infer<typeof selectChatMessageSchema>;
export type InsertChatMessage = z.infer<typeof insertChatMessageSchema>;
