/**
 * Curated exercise data from Free Exercise DB
 * This includes instructions for exercises that map to our default exercises
 *
 * Source: https://github.com/yuhonas/free-exercise-db (Public Domain)
 */

import type { ExerciseCategory, ExerciseType } from "../schema/exercise";
import { FREE_EXERCISE_DB_BASE_URL } from "./free-exercise-db-mapping";

export interface EnrichedExercise {
  name: string;
  description: string;
  category: ExerciseCategory;
  muscleGroups: string[];
  equipment: string;
  exerciseType: ExerciseType;
  // New fields from Free Exercise DB
  externalId: string | null;
  externalSource: "free-exercise-db" | null;
  primaryImage: string | null;
  images: string[];
  instructions: string[];
  level: "beginner" | "intermediate" | "expert" | null;
  force: "push" | "pull" | "static" | null;
  mechanic: "compound" | "isolation" | null;
}

/**
 * Helper to generate image URLs
 */
function getImages(externalId: string, count = 2): string[] {
  return Array.from(
    { length: count },
    (_, i) => `${FREE_EXERCISE_DB_BASE_URL}/${externalId}/${i}.jpg`,
  );
}

/**
 * Default exercises enriched with Free Exercise DB data
 */
export const enrichedExercises: EnrichedExercise[] = [
  // === CHEST ===
  {
    name: "Barbell Bench Press",
    description: "Lie on a flat bench and press a barbell from chest level to full arm extension.",
    category: "chest",
    muscleGroups: ["chest", "triceps", "front deltoids"],
    equipment: "barbell",
    exerciseType: "strength",
    externalId: "Barbell_Bench_Press_-_Medium_Grip",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Barbell_Bench_Press_-_Medium_Grip/0.jpg`,
    images: getImages("Barbell_Bench_Press_-_Medium_Grip"),
    instructions: [
      "Lie back on a flat bench. Using a medium width grip, lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.",
      "From the starting position, breathe in and begin coming down slowly until the bar touches your middle chest.",
      "After a brief pause, push the bar back to the starting position as you breathe out. Focus on pushing the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position at the top of the motion, hold for a second and then start coming down slowly again.",
      "Repeat the movement for the prescribed amount of repetitions.",
      "When you are done, place the bar back in the rack.",
    ],
    level: "beginner",
    force: "push",
    mechanic: "compound",
  },
  {
    name: "Incline Dumbbell Press",
    description: "Press dumbbells upward while lying on an incline bench set to 30-45 degrees.",
    category: "chest",
    muscleGroups: ["upper chest", "triceps", "front deltoids"],
    equipment: "dumbbell",
    exerciseType: "strength",
    externalId: "Incline_Dumbbell_Press",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Incline_Dumbbell_Press/0.jpg`,
    images: getImages("Incline_Dumbbell_Press"),
    instructions: [
      "Lie back on an incline bench with a dumbbell in each hand atop your thighs. The palms of your hands will be facing each other.",
      "Then, using your thighs to help push the dumbbells up, lift the dumbbells one at a time so that you can hold them at shoulder width.",
      "Once you have the dumbbells raised to shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. This will be your starting position.",
      "Be sure to keep full control of the dumbbells at all times. Then breathe out and push the dumbbells up with your chest.",
      "Lock your arms at the top, hold for a second, and then start slowly lowering the weight. Tip: Ideally, lowering the weights should take about twice as long as raising them.",
      "Repeat the movement for the prescribed amount of repetitions.",
    ],
    level: "beginner",
    force: "push",
    mechanic: "compound",
  },
  {
    name: "Dumbbell Fly",
    description:
      "Lie on a flat bench and lower dumbbells in an arc to the sides, then bring them back together.",
    category: "chest",
    muscleGroups: ["chest"],
    equipment: "dumbbell",
    exerciseType: "strength",
    externalId: "Dumbbell_Flyes",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Dumbbell_Flyes/0.jpg`,
    images: getImages("Dumbbell_Flyes"),
    instructions: [
      "Lie down on a flat bench with a dumbbell on each hand resting on top of your thighs. The palms of your hand will be facing each other.",
      "Then using your thighs to help raise the dumbbells, lift the dumbbells one at a time so you can hold them in front of you at shoulder width with the palms of your hands facing each other. Raise the dumbbells up like you're pressing them, but stop and hold just before you lock out. This will be your starting position.",
      "With a slight bend on your elbows in order to prevent stress at the biceps tendon, lower your arms out at both sides in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement.",
      "Return your arms back to the starting position as you squeeze your chest muscles and breathe out.",
      "Hold for a second at the contracted position and repeat the movement for the prescribed amount of repetitions.",
    ],
    level: "beginner",
    force: "push",
    mechanic: "isolation",
  },
  {
    name: "Push-up",
    description:
      "Start in a plank position and lower your body until your chest nearly touches the floor, then push back up.",
    category: "chest",
    muscleGroups: ["chest", "triceps", "front deltoids", "core"],
    equipment: "bodyweight",
    exerciseType: "strength",
    externalId: "Pushups",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Pushups/0.jpg`,
    images: getImages("Pushups"),
    instructions: [
      "Lie on the floor face down and place your hands about 36 inches apart while holding your torso up at arms length.",
      "Next, lower yourself downward until your chest almost touches the floor as you inhale.",
      "Now breathe out and press your upper body back up to the starting position while squeezing your chest.",
      "After a brief pause at the top contracted position, you can begin to lower yourself downward again for as many repetitions as needed.",
    ],
    level: "beginner",
    force: "push",
    mechanic: "compound",
  },
  {
    name: "Cable Crossover",
    description: "Pull cable handles from high position down and across your body.",
    category: "chest",
    muscleGroups: ["chest", "front deltoids"],
    equipment: "cable",
    exerciseType: "strength",
    externalId: "Cable_Crossover",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Cable_Crossover/0.jpg`,
    images: getImages("Cable_Crossover"),
    instructions: [
      "To get yourself into the starting position, place the pulleys on a high position (above your head), select the resistance to be used and hold the pulleys in each hand.",
      "Step forward in front of an imaginary straight line between both pulleys while pulling your arms together in front of you. Your torso should have a small forward bend from the waist. This will be your starting position.",
      "With a slight bend on your elbows in order to prevent stress at the biceps tendon, extend your arms to the side (straight out at both sides) in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement.",
      "Return your arms back to the starting position as you breathe out. Make sure to use the same arc of motion used to lower the weights.",
      "Hold for a second at the starting position and repeat the movement for the prescribed amount of repetitions.",
    ],
    level: "beginner",
    force: "push",
    mechanic: "isolation",
  },
  {
    name: "Decline Bench Press",
    description: "Press a barbell while lying on a decline bench.",
    category: "chest",
    muscleGroups: ["lower chest", "triceps"],
    equipment: "barbell",
    exerciseType: "strength",
    externalId: "Decline_Barbell_Bench_Press",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Decline_Barbell_Bench_Press/0.jpg`,
    images: getImages("Decline_Barbell_Bench_Press"),
    instructions: [
      "Secure your legs at the end of the decline bench and lie down with a barbell using a medium width grip.",
      "Once you are laying down, lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.",
      "As you breathe in, come down slowly until you feel the bar on your lower chest.",
      "After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position, hold for a second and then start coming down slowly again.",
      "Repeat the movement for the prescribed amount of repetitions.",
    ],
    level: "intermediate",
    force: "push",
    mechanic: "compound",
  },

  // === BACK ===
  {
    name: "Barbell Deadlift",
    description: "Lift a barbell from the floor to hip level by extending your hips and knees.",
    category: "back",
    muscleGroups: ["lower back", "glutes", "hamstrings", "traps"],
    equipment: "barbell",
    exerciseType: "strength",
    externalId: "Barbell_Deadlift",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Barbell_Deadlift/0.jpg`,
    images: getImages("Barbell_Deadlift"),
    instructions: [
      "Stand in front of a loaded barbell.",
      "While keeping the back as straight as possible, bend your knees, bend forward and grasp the bar using a medium (shoulder width) overhand grip.",
      "While holding the bar, start the lift by pushing with your legs while simultaneously getting your torso to the upright position as you breathe out.",
      "In the upright position, stick your chest out and contract the back by bringing the shoulder blades back.",
      "Go back to the starting position by bending at the knees while simultaneously leaning the torso forward at the waist while keeping the back straight.",
      "Perform the amount of repetitions prescribed in the program.",
    ],
    level: "intermediate",
    force: "pull",
    mechanic: "compound",
  },
  {
    name: "Pull-up",
    description: "Hang from a bar and pull yourself up until your chin is above the bar.",
    category: "back",
    muscleGroups: ["lats", "biceps", "rear deltoids"],
    equipment: "pull-up bar",
    exerciseType: "strength",
    externalId: "Pullups",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Pullups/0.jpg`,
    images: getImages("Pullups"),
    instructions: [
      "Grab the pull-up bar with the palms facing forward using the prescribed grip.",
      "As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.",
      "Pull your torso up until the bar touches your upper chest by drawing the shoulders and the upper arms down and back. Breathe out as you perform this portion of the movement.",
      "After a second on the contracted position, start to inhale and slowly lower your torso back to the starting position when your arms are fully extended and the lats are fully stretched.",
      "Repeat this motion for the prescribed amount of repetitions.",
    ],
    level: "beginner",
    force: "pull",
    mechanic: "compound",
  },
  {
    name: "Bent Over Barbell Row",
    description: "Bend at the hips and pull a barbell to your lower chest/upper abdomen.",
    category: "back",
    muscleGroups: ["lats", "rhomboids", "rear deltoids", "biceps"],
    equipment: "barbell",
    exerciseType: "strength",
    externalId: "Bent_Over_Barbell_Row",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Bent_Over_Barbell_Row/0.jpg`,
    images: getImages("Bent_Over_Barbell_Row"),
    instructions: [
      "Holding a barbell with a pronated grip (palms facing down), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor.",
      "Now, while keeping the torso stationary, breathe out and lift the barbell to you. Keep the elbows close to the body and only use the forearms to hold the weight.",
      "At the top contracted position, squeeze the back muscles and hold for a brief pause.",
      "Then inhale and slowly lower the barbell back to the starting position.",
      "Repeat for the recommended amount of repetitions.",
    ],
    level: "beginner",
    force: "pull",
    mechanic: "compound",
  },
  {
    name: "Lat Pulldown",
    description: "Pull a cable bar down to your chest while seated.",
    category: "back",
    muscleGroups: ["lats", "biceps", "rear deltoids"],
    equipment: "cable",
    exerciseType: "strength",
    externalId: "Wide-Grip_Lat_Pulldown",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Wide-Grip_Lat_Pulldown/0.jpg`,
    images: getImages("Wide-Grip_Lat_Pulldown"),
    instructions: [
      "Sit down on a pull-down machine with a wide bar attached to the top pulley. Adjust the knee pad to fit snugly against your legs.",
      "Grab the bar with the palms facing forward. For a wide grip, your hands need to be spaced out at a distance wider than shoulder width.",
      "As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.",
      "As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back.",
      "After a second at the contracted position squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement.",
      "Repeat this motion for the prescribed amount of repetitions.",
    ],
    level: "beginner",
    force: "pull",
    mechanic: "compound",
  },
  {
    name: "Seated Cable Row",
    description: "Pull a cable handle to your abdomen while seated.",
    category: "back",
    muscleGroups: ["lats", "rhomboids", "rear deltoids", "biceps"],
    equipment: "cable",
    exerciseType: "strength",
    externalId: "Seated_Cable_Rows",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Seated_Cable_Rows/0.jpg`,
    images: getImages("Seated_Cable_Rows"),
    instructions: [
      "For this exercise you will need access to a low pulley row machine with a V-bar. Sit down on the machine and place your feet on the front platform or crossbar provided making sure that your knees are slightly bent and not locked.",
      "Lean over as you keep the natural alignment of your back and grab the V-bar handles.",
      "With your arms extended pull back until your torso is at a 90-degree angle from your legs. Your back should be slightly arched and your chest should be sticking out. This is the starting position of the exercise.",
      "Keeping the torso stationary, pull the handles back towards your torso while keeping the arms close to it until you touch the abdominals. Breathe out as you perform that movement. At that point you should be squeezing your back muscles hard.",
      "Hold that contraction for a second and slowly go back to the original position while breathing in.",
      "Repeat for the recommended amount of repetitions.",
    ],
    level: "beginner",
    force: "pull",
    mechanic: "compound",
  },
  {
    name: "Single-Arm Dumbbell Row",
    description: "Row a dumbbell to your hip while supporting yourself with the other hand.",
    category: "back",
    muscleGroups: ["lats", "rhomboids", "biceps"],
    equipment: "dumbbell",
    exerciseType: "strength",
    externalId: "One-Arm_Dumbbell_Row",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/One-Arm_Dumbbell_Row/0.jpg`,
    images: getImages("One-Arm_Dumbbell_Row"),
    instructions: [
      "Choose a flat bench and place a dumbbell on each side of it.",
      "Place the right leg on top of the end of the bench, bend your torso forward from the waist until your upper body is parallel to the floor, and place your right hand on the other end of the bench for support.",
      "Use the left hand to pick up the dumbbell on the floor and hold the weight while keeping your lower back straight. The palm of the hand should be facing your torso. This will be your starting position.",
      "Pull the resistance straight up to the side of your chest, keeping your upper arm close to your side and keeping the torso stationary. Breathe out as you perform this step.",
      "Lower the resistance straight down to the starting position. Breathe in as you perform this step.",
      "Repeat the movement for the specified amount of repetitions.",
      "Switch sides and repeat again with the other arm.",
    ],
    level: "beginner",
    force: "pull",
    mechanic: "compound",
  },

  // === SHOULDERS ===
  {
    name: "Overhead Press",
    description: "Press a barbell or dumbbells from shoulder level to overhead.",
    category: "shoulders",
    muscleGroups: ["front deltoids", "side deltoids", "triceps"],
    equipment: "barbell",
    exerciseType: "strength",
    externalId: "Standing_Military_Press",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Standing_Military_Press/0.jpg`,
    images: getImages("Standing_Military_Press"),
    instructions: [
      "Start by placing a barbell that is about chest high on a squat rack. Once you have selected the weights, grab the barbell using a pronated (palms facing forward) grip. Make sure to grip the bar wider than shoulder width apart from each other.",
      "Slightly bend the knees and place the barbell on your collar bone. Lift the barbell up keeping it lying on your chest. Take a step back and position your feet shoulder width apart from each other.",
      "Once you pick up the barbell with the correct grip length, lift the bar up over your head by locking your arms. Hold at about shoulder level and slightly in front of your head. This is your starting position.",
      "Lower the bar down to the collarbone slowly as you inhale.",
      "Lift the bar back up to the starting position as you exhale.",
      "Repeat for the recommended amount of repetitions.",
    ],
    level: "intermediate",
    force: "push",
    mechanic: "compound",
  },
  {
    name: "Lateral Raise",
    description: "Raise dumbbells out to the sides until arms are parallel to the floor.",
    category: "shoulders",
    muscleGroups: ["side deltoids"],
    equipment: "dumbbell",
    exerciseType: "strength",
    externalId: "Side_Lateral_Raise",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Side_Lateral_Raise/0.jpg`,
    images: getImages("Side_Lateral_Raise"),
    instructions: [
      "Pick a couple of dumbbells and stand with a straight torso and the dumbbells by your side at arms length with the palms of the hand facing you. This will be your starting position.",
      "While maintaining the torso in a stationary position, lift the dumbbells to your side with a slight bend on the elbow and the hands slightly tilted forward. Continue to go up until you arms are parallel to the floor. Exhale as you execute this movement and pause for a second at the top.",
      "Lower the dumbbells back down slowly to the starting position as you inhale.",
      "Repeat for the recommended amount of repetitions.",
    ],
    level: "beginner",
    force: "push",
    mechanic: "isolation",
  },
  {
    name: "Front Raise",
    description: "Raise dumbbells in front of you until arms are parallel to the floor.",
    category: "shoulders",
    muscleGroups: ["front deltoids"],
    equipment: "dumbbell",
    exerciseType: "strength",
    externalId: "Front_Dumbbell_Raise",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Front_Dumbbell_Raise/0.jpg`,
    images: getImages("Front_Dumbbell_Raise"),
    instructions: [
      "Pick a couple of dumbbells and stand with a straight torso and the dumbbells on front of your thighs at arms length with the palms of the hand facing your thighs. This will be your starting position.",
      "While maintaining the torso stationary, lift the left dumbbell to the front with a slight bend on the elbow and the palms of the hands always facing down. Continue to go up until you arm is slightly above parallel to the floor. Exhale as you execute this portion of the movement and pause for a second at the top.",
      "Inhale after the second pause at the top and slowly lower the dumbbell back down to the starting position.",
      "Now repeat with the right arm. Continue alternating in this fashion until you have performed the recommended amount of repetitions for each arm.",
    ],
    level: "beginner",
    force: "push",
    mechanic: "isolation",
  },
  {
    name: "Face Pull",
    description: "Pull a rope attachment toward your face, separating the ends.",
    category: "shoulders",
    muscleGroups: ["rear deltoids", "upper traps", "rotator cuff"],
    equipment: "cable",
    exerciseType: "strength",
    externalId: "Face_Pull",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Face_Pull/0.jpg`,
    images: getImages("Face_Pull"),
    instructions: [
      "Facing a high pulley with a rope or dual handles attached, pull the weight directly towards your face, separating your hands as you do so. Keep your upper arms parallel to the ground.",
    ],
    level: "beginner",
    force: "pull",
    mechanic: "isolation",
  },
  {
    name: "Arnold Press",
    description:
      "Press dumbbells overhead while rotating from palms facing you to palms facing forward.",
    category: "shoulders",
    muscleGroups: ["front deltoids", "side deltoids", "triceps"],
    equipment: "dumbbell",
    exerciseType: "strength",
    externalId: "Arnold_Dumbbell_Press",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Arnold_Dumbbell_Press/0.jpg`,
    images: getImages("Arnold_Dumbbell_Press"),
    instructions: [
      "Sit on an exercise bench with back support and hold two dumbbells in front of you at about upper chest level with your palms facing your body and your elbows bent. This is your starting position.",
      "Now to perform the movement, raise the dumbbells as you rotate the palms of your hands until they are facing forward.",
      "Continue lifting the dumbbells until your arms are extended above you in straight arm position. Breathe out as you perform this portion of the movement.",
      "After a second pause at the top, begin to lower the dumbbells to the original position by rotating the palms of your hands towards you. Breathe in as you perform this portion of the movement.",
      "Repeat for the recommended amount of repetitions.",
    ],
    level: "intermediate",
    force: "push",
    mechanic: "compound",
  },

  // === ARMS ===
  {
    name: "Barbell Curl",
    description: "Curl a barbell from arms extended to shoulder level.",
    category: "arms",
    muscleGroups: ["biceps", "forearms"],
    equipment: "barbell",
    exerciseType: "strength",
    externalId: "Barbell_Curl",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Barbell_Curl/0.jpg`,
    images: getImages("Barbell_Curl"),
    instructions: [
      "Stand up with your torso upright while holding a barbell at a shoulder-width grip. The palm of your hands should be facing forward and the elbows should be close to the torso. This will be your starting position.",
      "While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out. Only the forearms should move.",
      "Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second and squeeze the biceps hard.",
      "Slowly begin to bring the bar back to starting position as your breathe in.",
      "Repeat for the recommended amount of repetitions.",
    ],
    level: "beginner",
    force: "pull",
    mechanic: "isolation",
  },
  {
    name: "Dumbbell Curl",
    description: "Curl dumbbells from arms extended to shoulder level.",
    category: "arms",
    muscleGroups: ["biceps", "forearms"],
    equipment: "dumbbell",
    exerciseType: "strength",
    externalId: "Dumbbell_Bicep_Curl",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Dumbbell_Bicep_Curl/0.jpg`,
    images: getImages("Dumbbell_Bicep_Curl"),
    instructions: [
      "Stand up straight with a dumbbell in each hand at arm's length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position.",
      "Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps. Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level.",
      "Hold the contracted position for a brief pause as you squeeze your biceps.",
      "Then, inhale and slowly begin to lower the dumbbells back to the starting position.",
      "Repeat for the recommended amount of repetitions.",
    ],
    level: "beginner",
    force: "pull",
    mechanic: "isolation",
  },
  {
    name: "Hammer Curl",
    description: "Curl dumbbells with a neutral (hammer) grip.",
    category: "arms",
    muscleGroups: ["biceps", "brachialis", "forearms"],
    equipment: "dumbbell",
    exerciseType: "strength",
    externalId: "Hammer_Curls",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Hammer_Curls/0.jpg`,
    images: getImages("Hammer_Curls"),
    instructions: [
      "Stand up with your torso upright and a dumbbell on each hand being held at arms length. The elbows should be close to the torso.",
      "The palms of the hands should be facing your torso. This will be your starting position.",
      "Now, while holding your upper arm stationary, exhale and curl the weight forward while contracting the biceps. Continue to raise the weight until the biceps are fully contracted and the dumbbell is at shoulder level.",
      "Hold the contracted position for a brief moment as you squeeze the biceps.",
      "Then, inhale and slowly begin to lower the dumbbells back down to the starting position.",
      "Repeat for the recommended amount of repetitions.",
    ],
    level: "beginner",
    force: "pull",
    mechanic: "isolation",
  },
  {
    name: "Tricep Pushdown",
    description: "Push a cable attachment down from chest level to full arm extension.",
    category: "arms",
    muscleGroups: ["triceps"],
    equipment: "cable",
    exerciseType: "strength",
    externalId: "Triceps_Pushdown",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Triceps_Pushdown/0.jpg`,
    images: getImages("Triceps_Pushdown"),
    instructions: [
      "Attach a straight or angled bar to a high pulley and grab with an overhand grip at shoulder width.",
      "Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the bar. This is your starting position.",
      "Using the triceps, bring the bar down until it touches the front of your thighs and the arms are fully extended perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement.",
      "After a second hold at the contracted position, bring the bar slowly up to the starting point. Breathe in as you perform this step.",
      "Repeat for the recommended amount of repetitions.",
    ],
    level: "beginner",
    force: "push",
    mechanic: "isolation",
  },
  {
    name: "Skull Crusher",
    description:
      "Lower a barbell or dumbbells to your forehead while lying on a bench, then extend.",
    category: "arms",
    muscleGroups: ["triceps"],
    equipment: "barbell",
    exerciseType: "strength",
    externalId: "Lying_Triceps_Press",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Lying_Triceps_Press/0.jpg`,
    images: getImages("Lying_Triceps_Press"),
    instructions: [
      "Lie on a flat bench with either an e-z bar or a straight bar and extend your arms toward the ceiling.",
      "Now, keeping the upper arms stationary, lower the bar by allowing the elbows to flex. Inhale as you perform this portion of the movement. Pause once the bar is directly above the forehead.",
      "Lift the bar back to the starting position by extending the elbow and exhaling.",
      "Repeat.",
    ],
    level: "intermediate",
    force: "push",
    mechanic: "isolation",
  },
  {
    name: "Tricep Dip",
    description: "Lower and raise your body using parallel bars or a bench.",
    category: "arms",
    muscleGroups: ["triceps", "chest", "front deltoids"],
    equipment: "bodyweight",
    exerciseType: "strength",
    externalId: "Dips_-_Triceps_Version",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Dips_-_Triceps_Version/0.jpg`,
    images: getImages("Dips_-_Triceps_Version"),
    instructions: [
      "To get into the starting position, hold your body at arm's length with your arms nearly locked above the bars.",
      "Now, inhale and slowly lower yourself downward. Your torso should remain upright and your elbows should stay close to your body. This helps to better focus on tricep involvement.",
      "Lower yourself until there is a 90 degree angle formed between the upper arm and forearm.",
      "Then, exhale and push your torso back up using your triceps to bring your body back to the starting position.",
      "Repeat the movement for the prescribed amount of repetitions.",
    ],
    level: "intermediate",
    force: "push",
    mechanic: "compound",
  },

  // === LEGS ===
  {
    name: "Barbell Squat",
    description:
      "With a barbell on your upper back, bend your knees and hips to lower your body, then stand back up.",
    category: "legs",
    muscleGroups: ["quadriceps", "glutes", "hamstrings", "core"],
    equipment: "barbell",
    exerciseType: "strength",
    externalId: "Barbell_Full_Squat",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Barbell_Full_Squat/0.jpg`,
    images: getImages("Barbell_Full_Squat"),
    instructions: [
      "This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack just above shoulder level. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it.",
      "Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.",
      "Step away from the rack and position your legs using a shoulder-width medium stance with the toes slightly pointed out. Keep your head up at all times and maintain a straight back. This will be your starting position.",
      "Begin to slowly lower the bar by bending the knees and sitting back with your hips as you maintain a straight posture with the head up. Continue down until your hamstrings are on your calves. Inhale as you perform this portion of the movement.",
      "Begin to raise the bar as you exhale by pushing the floor with the heel or middle of your foot as you straighten the legs and extend the hips to go back to the starting position.",
      "Repeat for the recommended amount of repetitions.",
    ],
    level: "intermediate",
    force: "push",
    mechanic: "compound",
  },
  {
    name: "Leg Press",
    description: "Push a weighted platform away from your body using your legs.",
    category: "legs",
    muscleGroups: ["quadriceps", "glutes", "hamstrings"],
    equipment: "machine",
    exerciseType: "strength",
    externalId: "Leg_Press",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Leg_Press/0.jpg`,
    images: getImages("Leg_Press"),
    instructions: [
      "Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance.",
      "Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you. Your torso and the legs should make a perfect 90-degree angle. This will be your starting position.",
      "As you inhale, slowly lower the platform until your upper and lower legs make a 90-degree angle.",
      "Pushing mainly with the heels of your feet and using the quadriceps go back to the starting position as you exhale.",
      "Repeat for the recommended amount of repetitions and ensure to lock the safety pins properly once you are done.",
    ],
    level: "beginner",
    force: "push",
    mechanic: "compound",
  },
  {
    name: "Romanian Deadlift",
    description: "Lower a barbell by hinging at the hips while keeping legs relatively straight.",
    category: "legs",
    muscleGroups: ["hamstrings", "glutes", "lower back"],
    equipment: "barbell",
    exerciseType: "strength",
    externalId: "Romanian_Deadlift",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Romanian_Deadlift/0.jpg`,
    images: getImages("Romanian_Deadlift"),
    instructions: [
      "Hold a bar at hip level with a pronated (palms facing down) grip. Your shoulders should be back, your back arched, and your knees slightly bent. This will be your starting position.",
      "Lower the bar by moving your butt back as far as you can. Keep the bar close to your body, your head looking forward, and your shoulders back. Done correctly, you should reach the maximum range of your hamstring flexibility just below the knee.",
      "At the bottom of your range of motion, return the starting position by driving the hips forward to stand up tall.",
    ],
    level: "intermediate",
    force: "pull",
    mechanic: "compound",
  },
  {
    name: "Leg Curl",
    description: "Curl your heels toward your glutes against resistance.",
    category: "legs",
    muscleGroups: ["hamstrings"],
    equipment: "machine",
    exerciseType: "strength",
    externalId: "Lying_Leg_Curls",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Lying_Leg_Curls/0.jpg`,
    images: getImages("Lying_Leg_Curls"),
    instructions: [
      "Adjust the machine lever to fit your height and lie face down on the leg curl machine with the pad of the lever on the back of your legs (just a few inches under the calves).",
      "Keeping the torso flat on the bench, ensure your legs are fully stretched and grab the side handles of the machine. Position your toes straight. This will be your starting position.",
      "As you exhale, curl your legs up as far as possible without lifting the upper legs from the pad. Once you hit the fully contracted position, hold it for a second.",
      "As you inhale, bring the legs back to the initial position.",
      "Repeat for the recommended amount of repetitions.",
    ],
    level: "beginner",
    force: "pull",
    mechanic: "isolation",
  },
  {
    name: "Leg Extension",
    description: "Extend your legs against resistance while seated.",
    category: "legs",
    muscleGroups: ["quadriceps"],
    equipment: "machine",
    exerciseType: "strength",
    externalId: "Leg_Extensions",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Leg_Extensions/0.jpg`,
    images: getImages("Leg_Extensions"),
    instructions: [
      "For this exercise you will need to use a leg extension machine. First choose your weight and sit on the machine with your legs under the pad (feet pointed forward) and the hands holding the side bars. This will be your starting position.",
      "Using your quadriceps, extend your legs to the maximum as you exhale. Ensure that the rest of the body remains stationary on the seat. Pause a second on the contracted position.",
      "Slowly lower the weight back to the original position as you inhale, ensuring that you do not go past the 90-degree angle limit.",
      "Repeat for the recommended amount of times.",
    ],
    level: "beginner",
    force: "push",
    mechanic: "isolation",
  },
  {
    name: "Walking Lunge",
    description: "Step forward into a lunge, then bring the back leg forward to step again.",
    category: "legs",
    muscleGroups: ["quadriceps", "glutes", "hamstrings"],
    equipment: "bodyweight",
    exerciseType: "strength",
    externalId: "Dumbbell_Lunges",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Dumbbell_Lunges/0.jpg`,
    images: getImages("Dumbbell_Lunges"),
    instructions: [
      "Stand with your torso upright holding two dumbbells in your hands by your sides. This will be your starting position.",
      "Step forward with your right leg around 2 feet or so from the foot being left stationary behind and lower your upper body down, while keeping the torso upright and maintaining balance. Inhale as you go down.",
      "Do not allow your knee to go forward beyond your toes as you come down, as this will put undue stress on the knee joint. Make sure that you keep your front shin perpendicular to the ground.",
      "Using mainly the heel of your foot, push up and go back to the starting position as you exhale.",
      "Repeat the movement for the recommended amount of repetitions and then perform with the left leg.",
    ],
    level: "beginner",
    force: "push",
    mechanic: "compound",
  },
  {
    name: "Calf Raise",
    description: "Rise up on your toes, lifting your heels off the ground.",
    category: "legs",
    muscleGroups: ["calves"],
    equipment: "bodyweight",
    exerciseType: "strength",
    externalId: "Standing_Calf_Raises",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Standing_Calf_Raises/0.jpg`,
    images: getImages("Standing_Calf_Raises"),
    instructions: [
      "Adjust the padded lever of the calf raise machine to fit your height.",
      "Place your shoulders under the pads provided and position your toes facing forward. The balls of your feet should be secured on top of the calf block with the heels extending off it. Push the lever up by extending your hips and knees until your torso is standing erect. Your knees should be kept with a slight bend; never locked. This will be your starting position.",
      "Raise your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position by a second before you start to go back down.",
      "Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched.",
      "Repeat for the recommended amount of repetitions.",
    ],
    level: "beginner",
    force: "push",
    mechanic: "isolation",
  },

  // === CORE ===
  {
    name: "Plank",
    description: "Hold a push-up position with your body in a straight line.",
    category: "core",
    muscleGroups: ["core", "shoulders"],
    equipment: "bodyweight",
    exerciseType: "strength",
    externalId: "Plank",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Plank/0.jpg`,
    images: getImages("Plank"),
    instructions: [
      "Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder.",
      "Keep your body straight at all times, and hold this position as long as possible. To increase difficulty, an arm or leg can be raised.",
    ],
    level: "beginner",
    force: "static",
    mechanic: "isolation",
  },
  {
    name: "Crunch",
    description: "Lie on your back and curl your shoulders toward your pelvis.",
    category: "core",
    muscleGroups: ["abs"],
    equipment: "bodyweight",
    exerciseType: "strength",
    externalId: "Crunches",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Crunches/0.jpg`,
    images: getImages("Crunches"),
    instructions: [
      "Lie flat on your back with your feet flat on the ground, or resting on a bench with your knees bent at a 90 degree angle. If you are resting your feet on a bench, place them three to four inches apart and point your toes inward so they touch.",
      "Now place your hands lightly on either side of your head keeping your elbows in. Don't lock your fingers behind your head.",
      "While pushing the small of your back down in the floor to better isolate your abdominal muscles, begin to roll your shoulders off the floor.",
      "Continue to push down as hard as you can with your lower back as you contract your abdominals and exhale. Your shoulders should come up off the floor only about four inches, and your lower back should remain on the floor. At the top of the movement, contract your abdominals hard and keep the contraction for a second.",
      "After the one second contraction, begin to come down slowly again to the starting position as you inhale.",
      "Repeat for the recommended amount of repetitions.",
    ],
    level: "beginner",
    force: "pull",
    mechanic: "isolation",
  },
  {
    name: "Russian Twist",
    description: "Sit with knees bent and rotate your torso side to side.",
    category: "core",
    muscleGroups: ["obliques", "abs"],
    equipment: "bodyweight",
    exerciseType: "strength",
    externalId: "Russian_Twist",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Russian_Twist/0.jpg`,
    images: getImages("Russian_Twist"),
    instructions: [
      "Lie down on the floor placing your feet either under something that will not move or by having a partner hold them. Your legs should be bent at the knees.",
      "Elevate your upper body so that it creates an imaginary V-shape with your thighs. Your arms should be fully extended in front of you perpendicular to your torso and with the hands clasped. This is the starting position.",
      "Twist your torso to the right side until your arms are parallel with the floor while breathing out.",
      "Hold the contraction for a second and move back to the starting position while breathing out. Now move to the opposite side performing the same techniques you applied to the right side.",
      "Repeat for the recommended amount of repetitions.",
    ],
    level: "beginner",
    force: "pull",
    mechanic: "compound",
  },
  {
    name: "Hanging Leg Raise",
    description: "Hang from a bar and raise your legs to horizontal or higher.",
    category: "core",
    muscleGroups: ["lower abs", "hip flexors"],
    equipment: "pull-up bar",
    exerciseType: "strength",
    externalId: "Hanging_Leg_Raise",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Hanging_Leg_Raise/0.jpg`,
    images: getImages("Hanging_Leg_Raise"),
    instructions: [
      "Hang from a chin-up bar with both arms extended at arms length in top of you using either a wide grip or a medium grip. The legs should be straight down with the pelvis rolled slightly backwards. This will be your starting position.",
      "Raise your legs until the torso makes a 90-degree angle with the legs. Exhale as you perform this movement and hold the contraction for a second or so.",
      "Go back slowly to the starting position as you breathe in.",
      "Repeat for the recommended amount of repetitions.",
    ],
    level: "intermediate",
    force: "pull",
    mechanic: "isolation",
  },
  {
    name: "Dead Bug",
    description:
      "Lie on your back and alternately extend opposite arm and leg while keeping core engaged.",
    category: "core",
    muscleGroups: ["abs", "core"],
    equipment: "bodyweight",
    exerciseType: "strength",
    externalId: null, // Not in Free Exercise DB
    externalSource: null,
    primaryImage: null,
    images: [],
    instructions: [
      "Lie on your back with your arms extended toward the ceiling and your legs raised with knees bent at 90 degrees.",
      "Slowly lower your right arm behind your head while simultaneously extending your left leg, keeping both just above the floor.",
      "Keep your lower back pressed into the floor throughout the movement.",
      "Return to the starting position and repeat on the opposite side.",
      "Continue alternating sides for the recommended number of repetitions.",
    ],
    level: "beginner",
    force: "static",
    mechanic: "isolation",
  },
  {
    name: "Ab Wheel Rollout",
    description: "Roll an ab wheel forward while maintaining a straight body.",
    category: "core",
    muscleGroups: ["abs", "core", "shoulders"],
    equipment: "ab wheel",
    exerciseType: "strength",
    externalId: "Ab_Roller",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Ab_Roller/0.jpg`,
    images: getImages("Ab_Roller"),
    instructions: [
      "Hold the Ab Roller with both hands and kneel on the floor.",
      "Now place the ab roller on the floor in front of you so that you are on all your hands and knees. This will be your starting position.",
      "Slowly roll the ab roller straight forward, stretching your body into a straight position. Go down as far as you can without touching the floor with your body. Breathe in during this portion of the movement.",
      "After a pause at the stretched position, start pulling yourself back to the starting position as you breathe out. Go slowly and keep your abs tight at all times.",
    ],
    level: "intermediate",
    force: "pull",
    mechanic: "compound",
  },

  // === CARDIO ===
  {
    name: "Running",
    description: "Continuous running at a steady or varied pace.",
    category: "cardio",
    muscleGroups: ["legs", "cardiovascular system"],
    equipment: "none",
    exerciseType: "cardio",
    externalId: "Running_Treadmill",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Running_Treadmill/0.jpg`,
    images: getImages("Running_Treadmill"),
    instructions: [
      "To begin, step onto the treadmill and select the desired option from the menu. Most treadmills have a manual setting, or you can select a program to run.",
      "Start at a walking pace and gradually increase the speed until you reach a comfortable running pace.",
      "Keep your head up and look straight ahead. Maintain good posture with your shoulders back and core engaged.",
      "Land softly on the middle of your foot and roll through to push off with your toes.",
      "Continue running at your desired pace for the recommended duration.",
    ],
    level: "beginner",
    force: null,
    mechanic: null,
  },
  {
    name: "Cycling",
    description: "Pedaling on a bicycle or stationary bike.",
    category: "cardio",
    muscleGroups: ["legs", "cardiovascular system"],
    equipment: "bicycle",
    exerciseType: "cardio",
    externalId: null, // Generic cycling not in Free Exercise DB
    externalSource: null,
    primaryImage: null,
    images: [],
    instructions: [
      "Adjust the seat height so that your leg is almost fully extended at the bottom of the pedal stroke.",
      "Begin pedaling at a comfortable pace to warm up.",
      "Gradually increase your speed or resistance to reach your target intensity.",
      "Maintain a steady cadence and keep your core engaged for stability.",
      "Continue for the recommended duration, then cool down with slower pedaling.",
    ],
    level: "beginner",
    force: "push",
    mechanic: null,
  },
  {
    name: "Rowing",
    description: "Using a rowing machine with proper form.",
    category: "cardio",
    muscleGroups: ["back", "legs", "arms", "cardiovascular system"],
    equipment: "rowing machine",
    exerciseType: "cardio",
    externalId: null, // Rowing machine cardio not in Free Exercise DB
    externalSource: null,
    primaryImage: null,
    images: [],
    instructions: [
      "Sit on the rowing machine and secure your feet in the straps. Grab the handle with an overhand grip.",
      "Start with your knees bent and your body leaning slightly forward from the hips, arms extended.",
      "Push with your legs first, keeping your arms straight until your legs are almost extended.",
      "Then lean back slightly and pull the handle to your lower chest.",
      "Reverse the motion: extend your arms, lean forward, then bend your knees to return to start.",
      "Maintain a smooth, continuous motion and keep your core engaged throughout.",
    ],
    level: "beginner",
    force: "pull",
    mechanic: "compound",
  },
  {
    name: "Jump Rope",
    description: "Jumping over a rope swung under your feet.",
    category: "cardio",
    muscleGroups: ["calves", "shoulders", "cardiovascular system"],
    equipment: "jump rope",
    exerciseType: "cardio",
    externalId: null, // Jump rope not in Free Exercise DB
    externalSource: null,
    primaryImage: null,
    images: [],
    instructions: [
      "Hold the rope handles at hip height with your elbows close to your sides.",
      "Rotate your wrists to swing the rope over your head.",
      "Jump just high enough to clear the rope, landing softly on the balls of your feet.",
      "Keep your knees slightly bent and your core engaged throughout.",
      "Maintain a steady rhythm and continue for the recommended duration.",
    ],
    level: "beginner",
    force: "push",
    mechanic: null,
  },
  {
    name: "Swimming",
    description: "Various swimming strokes in a pool.",
    category: "cardio",
    muscleGroups: ["full body", "cardiovascular system"],
    equipment: "pool",
    exerciseType: "cardio",
    externalId: null, // Swimming not in Free Exercise DB
    externalSource: null,
    primaryImage: null,
    images: [],
    instructions: [
      "Enter the pool and begin with a few easy laps to warm up.",
      "Choose your stroke (freestyle, breaststroke, backstroke, or butterfly).",
      "Maintain proper form for your chosen stroke, focusing on smooth, efficient movements.",
      "Breathe rhythmically and keep your body streamlined in the water.",
      "Continue swimming for the recommended duration or distance.",
    ],
    level: "beginner",
    force: null,
    mechanic: null,
  },
  {
    name: "Stair Climbing",
    description: "Walking or running up stairs or using a stair machine.",
    category: "cardio",
    muscleGroups: ["legs", "glutes", "cardiovascular system"],
    equipment: "stairs",
    exerciseType: "cardio",
    externalId: null, // Stair climbing not in Free Exercise DB
    externalSource: null,
    primaryImage: null,
    images: [],
    instructions: [
      "Stand at the bottom of the stairs or step onto the stair machine.",
      "Begin stepping up at a comfortable pace, one step at a time.",
      "Keep your posture upright and engage your core for stability.",
      "Push through your heels to engage your glutes and hamstrings.",
      "Continue climbing for the recommended duration, then cool down.",
    ],
    level: "beginner",
    force: "push",
    mechanic: null,
  },
  {
    name: "Burpee",
    description:
      "Drop to the floor, do a push-up, jump your feet forward, and jump up with arms overhead.",
    category: "cardio",
    muscleGroups: ["full body", "cardiovascular system"],
    equipment: "bodyweight",
    exerciseType: "cardio",
    externalId: "Burpee",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Burpee/0.jpg`,
    images: getImages("Burpee"),
    instructions: [
      "Begin standing with your legs shoulder-width apart.",
      "Place your hands on the floor and kick your legs back so you end up with your stomach and thighs on the floor. Your elbows should be bent.",
      "From this position, press up like you're doing a push-up and push your hips up.",
      "Jump your feet under your hips and stand.",
      "Finish the movement by jumping in the air and bringing your hands over your head.",
      "Repeat for the recommended number of repetitions.",
    ],
    level: "intermediate",
    force: "push",
    mechanic: "compound",
  },

  // === FLEXIBILITY ===
  {
    name: "Hamstring Stretch",
    description: "Stretch your hamstrings by reaching toward your toes.",
    category: "flexibility",
    muscleGroups: ["hamstrings"],
    equipment: "none",
    exerciseType: "flexibility",
    externalId: null, // Generic hamstring stretch not in Free Exercise DB
    externalSource: null,
    primaryImage: null,
    images: [],
    instructions: [
      "Sit on the floor with your legs extended in front of you.",
      "Keeping your back straight, hinge at the hips and reach toward your toes.",
      "Go only as far as comfortable without rounding your back excessively.",
      "Hold the stretch for 20-30 seconds while breathing deeply.",
      "Slowly return to the starting position.",
    ],
    level: "beginner",
    force: "static",
    mechanic: null,
  },
  {
    name: "Hip Flexor Stretch",
    description: "Kneel on one knee and push your hips forward to stretch the hip flexors.",
    category: "flexibility",
    muscleGroups: ["hip flexors", "quadriceps"],
    equipment: "none",
    exerciseType: "flexibility",
    externalId: "Kneeling_Hip_Flexor",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Kneeling_Hip_Flexor/0.jpg`,
    images: getImages("Kneeling_Hip_Flexor"),
    instructions: [
      "Kneel on your right knee on a soft surface. Your left foot should be flat on the floor in front of you with your knee bent at 90 degrees.",
      "Place your hands on your left thigh for support.",
      "Keeping your back straight, push your hips forward until you feel a stretch in the front of your right hip.",
      "Hold the stretch for 20-30 seconds while breathing deeply.",
      "Switch sides and repeat with the left leg.",
    ],
    level: "beginner",
    force: "static",
    mechanic: null,
  },
  {
    name: "Chest Stretch",
    description: "Stretch your chest by extending your arm against a wall or doorframe.",
    category: "flexibility",
    muscleGroups: ["chest", "front deltoids"],
    equipment: "none",
    exerciseType: "flexibility",
    externalId: null, // Chest stretch not in Free Exercise DB
    externalSource: null,
    primaryImage: null,
    images: [],
    instructions: [
      "Stand in a doorway or next to a wall.",
      "Place your forearm against the wall with your elbow at shoulder height.",
      "Slowly rotate your body away from your arm until you feel a stretch in your chest.",
      "Hold for 20-30 seconds while breathing deeply.",
      "Switch sides and repeat.",
    ],
    level: "beginner",
    force: "static",
    mechanic: null,
  },
  {
    name: "Cat-Cow Stretch",
    description: "On hands and knees, alternate between arching and rounding your back.",
    category: "flexibility",
    muscleGroups: ["spine", "core"],
    equipment: "none",
    exerciseType: "flexibility",
    externalId: "Cat_Stretch",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Cat_Stretch/0.jpg`,
    images: getImages("Cat_Stretch"),
    instructions: [
      "Start on your hands and knees with your wrists directly under your shoulders and knees under your hips.",
      "For the Cat position: Exhale and round your spine toward the ceiling, tucking your chin to your chest.",
      "For the Cow position: Inhale and arch your back, lifting your head and tailbone toward the ceiling.",
      "Flow smoothly between these two positions, coordinating with your breath.",
      "Continue for 10-15 repetitions.",
    ],
    level: "beginner",
    force: "static",
    mechanic: null,
  },
  {
    name: "Shoulder Stretch",
    description: "Pull one arm across your body to stretch the shoulder.",
    category: "flexibility",
    muscleGroups: ["shoulders", "upper back"],
    equipment: "none",
    exerciseType: "flexibility",
    externalId: "Shoulder_Stretch",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Shoulder_Stretch/0.jpg`,
    images: getImages("Shoulder_Stretch"),
    instructions: [
      "Stand or sit with good posture.",
      "Bring your right arm across your chest.",
      "Use your left hand to gently pull your right arm closer to your body.",
      "Hold the stretch for 20-30 seconds while breathing deeply.",
      "Release and repeat on the other side.",
    ],
    level: "beginner",
    force: "static",
    mechanic: null,
  },
  {
    name: "Pigeon Pose",
    description: "A yoga pose that deeply stretches the hip rotators and hip flexors.",
    category: "flexibility",
    muscleGroups: ["hip rotators", "hip flexors", "glutes"],
    equipment: "none",
    exerciseType: "flexibility",
    externalId: null, // Pigeon pose not in Free Exercise DB
    externalSource: null,
    primaryImage: null,
    images: [],
    instructions: [
      "Start in a tabletop position on your hands and knees.",
      "Bring your right knee forward and place it behind your right wrist.",
      "Extend your left leg straight back behind you.",
      "Lower your hips toward the floor, keeping them square.",
      "Hold for 30 seconds to 2 minutes, breathing deeply.",
      "Switch sides and repeat.",
    ],
    level: "intermediate",
    force: "static",
    mechanic: null,
  },
  {
    name: "Child's Pose",
    description: "A resting yoga pose that stretches the back, hips, and thighs.",
    category: "flexibility",
    muscleGroups: ["back", "hips", "thighs"],
    equipment: "none",
    exerciseType: "flexibility",
    externalId: null, // Child's pose not in Free Exercise DB
    externalSource: null,
    primaryImage: null,
    images: [],
    instructions: [
      "Kneel on the floor with your big toes touching and knees spread apart.",
      "Sit back on your heels and fold forward, extending your arms in front of you.",
      "Rest your forehead on the floor and relax your entire body.",
      "Breathe deeply and hold for 30 seconds to several minutes.",
      "To release, walk your hands back and slowly rise up.",
    ],
    level: "beginner",
    force: "static",
    mechanic: null,
  },
  {
    name: "Downward Dog",
    description: "An inverted V-shape yoga pose that stretches the entire posterior chain.",
    category: "flexibility",
    muscleGroups: ["hamstrings", "calves", "shoulders", "back"],
    equipment: "none",
    exerciseType: "flexibility",
    externalId: null, // Downward dog not in Free Exercise DB
    externalSource: null,
    primaryImage: null,
    images: [],
    instructions: [
      "Start on your hands and knees with hands shoulder-width apart.",
      "Tuck your toes and lift your hips up and back, straightening your legs.",
      "Press your chest toward your thighs and your heels toward the floor.",
      "Keep your head between your arms and relax your neck.",
      "Hold for 30 seconds to 2 minutes, breathing deeply.",
    ],
    level: "beginner",
    force: "static",
    mechanic: null,
  },

  // === COMPOUND ===
  {
    name: "Clean and Press",
    description: "Lift a barbell from the floor to your shoulders (clean), then press it overhead.",
    category: "compound",
    muscleGroups: ["full body"],
    equipment: "barbell",
    exerciseType: "strength",
    externalId: "Clean_and_Press",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Clean_and_Press/0.jpg`,
    images: getImages("Clean_and_Press"),
    instructions: [
      "Assume a shoulder-width stance with the barbell on the floor in front of you. Bend at the hips and knees to grip the bar with an overhand grip slightly wider than shoulder width.",
      "Pull the bar from the floor by extending your hips and knees. As the bar rises, pull it close to your body and shrug your shoulders.",
      "As the bar reaches chest height, rotate your elbows under the bar and catch it on your front shoulders in a front squat position.",
      "Stand up from the squat position.",
      "Press the bar overhead by extending your arms while keeping your core tight.",
      "Lower the bar back to your shoulders, then to the floor, to complete one repetition.",
    ],
    level: "intermediate",
    force: "push",
    mechanic: "compound",
  },
  {
    name: "Thruster",
    description: "Combine a front squat with an overhead press in one fluid motion.",
    category: "compound",
    muscleGroups: ["quadriceps", "glutes", "shoulders", "triceps"],
    equipment: "barbell",
    exerciseType: "strength",
    externalId: "Thrusters",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Thrusters/0.jpg`,
    images: getImages("Thrusters"),
    instructions: [
      "Begin with a barbell in the front rack position, with your elbows high and the bar resting on your front shoulders.",
      "Perform a front squat by bending at the hips and knees, keeping your torso upright.",
      "Descend until your thighs are at least parallel to the floor.",
      "Drive up explosively through your heels, using the momentum to help press the bar overhead.",
      "Lock out your arms at the top, then lower the bar back to the front rack position.",
      "Repeat for the recommended number of repetitions.",
    ],
    level: "intermediate",
    force: "push",
    mechanic: "compound",
  },
  {
    name: "Turkish Get-Up",
    description:
      "Lie on your back holding a weight overhead and stand up while keeping it elevated.",
    category: "compound",
    muscleGroups: ["full body", "core", "shoulders"],
    equipment: "kettlebell",
    exerciseType: "strength",
    externalId: "Turkish_Get-Up",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Turkish_Get-Up/0.jpg`,
    images: getImages("Turkish_Get-Up"),
    instructions: [
      "Lie on your back with the kettlebell in your right hand, arm extended toward the ceiling. Bend your right knee with foot flat on the floor.",
      "Roll onto your left elbow, then your left hand, keeping your eyes on the kettlebell.",
      "Lift your hips off the ground into a bridge position.",
      "Sweep your left leg under your body and place your left knee on the ground.",
      "Remove your left hand from the floor and come to a kneeling position.",
      "Stand up while keeping the kettlebell overhead.",
      "Reverse the movement to return to the starting position.",
      "Complete all reps on one side before switching.",
    ],
    level: "intermediate",
    force: "push",
    mechanic: "compound",
  },
  {
    name: "Farmer's Walk",
    description: "Walk while carrying heavy weights at your sides.",
    category: "compound",
    muscleGroups: ["grip", "core", "traps", "legs"],
    equipment: "dumbbell",
    exerciseType: "strength",
    externalId: "Farmers_Walk",
    externalSource: "free-exercise-db",
    primaryImage: `${FREE_EXERCISE_DB_BASE_URL}/Farmers_Walk/0.jpg`,
    images: getImages("Farmers_Walk"),
    instructions: [
      "Pick up heavy dumbbells or farmer's walk handles from the floor using proper deadlift form.",
      "Stand tall with your shoulders back and core engaged.",
      "Walk forward with short, quick steps while maintaining good posture.",
      "Keep your grip tight and your arms straight at your sides.",
      "Walk for the recommended distance or time, then set the weights down with control.",
    ],
    level: "beginner",
    force: "static",
    mechanic: "compound",
  },
];
